/*
 * This source file was generated by the Gradle 'init' task
 */
package IRCTC.app.src.test.java.ticketbooking;
import IRCTC.app.src.main.java.ticketbooking.App;
public class AppTest {
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    private void assertNotNull(String string, String greeting) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'assertNotNull'");
    }
}
